## 
## -------------------------------------------------------------
##    Copyright 2010-2011 Synopsys, Inc.
##    All Rights Reserved Worldwide
## 
##    Licensed under the Apache License, Version 2.0 (the
##    "License"); you may not use this file except in
##    compliance with the License.  You may obtain a copy of
##    the License at
## 
##        http://www.apache.org/licenses/LICENSE-2.0
## 
##    Unless required by applicable law or agreed to in
##    writing, software distributed under the License is
##    distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
##    CONDITIONS OF ANY KIND, either express or implied.  See
##    the License for the specific language governing
##    permissions and limitations under the License.
## -------------------------------------------------------------
## 

UVM_HOME	= ../../../uvm-1.2/

include ../../../uvm-1.2/examples/Makefile.vcs


all: comp run

comp:
	$(VCS) +incdir+../rtl \
	       +incdir+../sv \
		vedic_adder_tb_top.sv +define+UVM_USE_RESOURCE_CONVERTER +UVM_VERBOSITY=UVM_HIGH +UVM_TESTNAME=base_test_c

run:
	$(SIMV) +UVM_TESTNAME=base_test_c
	$(CHECK)
